### ISSUE TITLE
Note Type Add on- error directly upon opening

### ISSUE THREAD

**Issue by ankidoc** [AnKingMed/AnKing-Note-Types#28]
Anki Version 2.1.45

OS: MacOS Big sur 11.6.1

Note Type: AnKing--Release_0.1-beta 

directly after installing and reopening Anki, clicking on the add on gives me this error message.

Error message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.45 (355e66e8) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-07 19:21:21
Add-ons possibly involved: ⁨AnKing Notetypes⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/gui/menu.py", line 10, in <lambda>
    a.triggered.connect(lambda: func())  # type: ignore
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/config.py", line 68, in open
    self._read_in_settings()
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/config.py", line 348, in _read_in_settings
    self._read_in_general_settings()
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/config.py", line 381, in _read_in_general_settings
    ntss = self._ntss_for_model(model)
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/config.py", line 252, in _ntss_for_model
    if nts.is_present(model):
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/notetype_setting.py", line 63, in is_present
    relevant_template_text = self._relevant_template_text(model)
  File "/Users/Lukas/Library/Application Support/Anki2/addons21/anking_notetypes/notetype_setting.py", line 125, in _relevant_template_text
    templates = model["tmpls"]
TypeError: 'NoneType' object is not subscriptable

**Comment by AnKingMed** [comment]
Have you updated to the latest note types already?

**Comment by ankidoc** [comment]
thanks for answering!

yes. I went to the relases tab on GitHub. The only note type I'm using is AnKing--Release_0.1-beta.

**Comment by AnKingMed** [comment]
Cool. I'll have @RisingOrange look into it

**Comment by AnKingMed** [comment]
Just published a new note type add-on on patreon/memberships. That should fix this bug. Thanks for the report!

**Comment by ankidoc** [comment]
I have to thank you! 
It works. 
Just want to say thanks for all your work and the super speedy support!
