### ISSUE TITLE
Error when trying to update notetypes

### ISSUE THREAD

**Issue by sriharshakoduru** [AnKingMed/AnKing-Note-Types#69]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-15 09:10:51
Add-ons possibly involved: ⁨AnKing Note Types Easy Customization⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "/Users/harsha/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 393, in on_done
    updated = updated_models_fut.result()
  File "concurrent.futures._base", line 438, in result
  File "concurrent.futures._base", line 390, in __get_result
  File "concurrent.futures.thread", line 52, in run
  File "/Users/harsha/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 379, in task
    self._update_notetype_to_newest_version(model)
AttributeError: 'NotetypesConfigWindow' object has no attribute '_update_notetype_to_newest_version'

**Comment by RisingOrange** [comment]
There is a new version of the add-on on AnkiHub. With it this error shouldn't happen anymore.

You may have to check for add-on updates in Anki. (Tools -> Add-ons -> Check for Updates)
